#!/usr/bin/env tsx
// Decrypt a TrustSwap daemon keystore and run a command with the
// resulting private key exported as `ENS_PRIVATE_KEY` (the env var the
// synthesis `ensemble` CLI reads).
//
// Why this exists: ensemble's writable commands (`agent register`,
// `agent link`, `context set`, `edit txt …`) sign with whatever key is
// in `ENS_PRIVATE_KEY`. Our daemon owner keys live encrypted in
// `~/.synthesis/<slug>-keystore.json` (mode 0600, scrypt + aes-256-ctr,
// matching scripts/provision-daemon.ts). This wrapper bridges the two:
// prompt for the password (or read from `SYNTHESIS_DAEMON_KEYSTORE_PASSWORD`),
// decrypt in memory, spawn the child command with `ENS_PRIVATE_KEY` set,
// and never write the plaintext key to disk or scroll it past the
// terminal.
//
// Usage:
//   pnpm tsx scripts/run-with-daemon-key.ts \
//     --keystore ~/.synthesis/daemon-trustrust-keystore.json \
//     -- ensemble agent register daemon.trustrust.eth --link true --chain base

import { existsSync, readFileSync } from "node:fs";
import { homedir } from "node:os";
import { createInterface } from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import { spawn } from "node:child_process";
import {
  scrypt,
  createDecipheriv,
  createHash,
  timingSafeEqual,
  type ScryptOptions,
} from "node:crypto";

// Wrap node:crypto's callback-style `scrypt` in a Promise. Inlined rather
// than going through `util.promisify` so we can pass the keystore's own
// `kdfparams.{n,r,p}` through the optional 4th argument — promisify
// generics don't reach the options-aware overload cleanly.
function scryptAsync(
  password: Buffer | string,
  salt: Buffer | string,
  keylen: number,
  options: ScryptOptions,
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    scrypt(password, salt, keylen, options, (err, derivedKey) => {
      if (err) reject(err);
      else resolve(derivedKey);
    });
  });
}

interface EncryptedKeystore {
  version: number;
  crypto: {
    cipher: string;
    ciphertext: string;
    cipherparams: { iv: string };
    kdf: string;
    kdfparams: { salt: string; n: number; r: number; p: number; dklen: number };
    mac: string;
  };
}

async function decryptKeystore(
  keystore: EncryptedKeystore,
  password: string,
): Promise<string> {
  const { kdfparams, ciphertext, cipherparams, mac, cipher } = keystore.crypto;
  if (cipher !== "aes-256-ctr" || keystore.crypto.kdf !== "scrypt") {
    throw new Error("unsupported keystore format");
  }
  // Honor the keystore's own KDF cost parameters. Node's scrypt defaults
  // (N=16384, r=8, p=1) match what scripts/provision-daemon.ts writes
  // today, but a keystore generated by any other tool — or by a future
  // provision-daemon revision — may use higher costs, and ignoring them
  // would surface as a MAC mismatch on a perfectly valid password.
  const dk = await scryptAsync(
    password,
    Buffer.from(kdfparams.salt, "hex"),
    kdfparams.dklen ?? 32,
    { N: kdfparams.n, r: kdfparams.r, p: kdfparams.p },
  );
  const ctBuf = Buffer.from(ciphertext, "hex");
  const expectedMac = createHash("sha256")
    .update(Buffer.concat([dk.subarray(16, 32), ctBuf]))
    .digest();
  if (!timingSafeEqual(expectedMac, Buffer.from(mac, "hex"))) {
    throw new Error("MAC mismatch — wrong password");
  }
  const decipher = createDecipheriv(
    "aes-256-ctr",
    dk,
    Buffer.from(cipherparams.iv, "hex"),
  );
  return `0x${Buffer.concat([decipher.update(ctBuf), decipher.final()]).toString("hex")}`;
}

/**
 * Read a password from stdin without echoing. Falls back to a normal
 * (echoed) read when stdin isn't a TTY, e.g. piped input in CI — raw
 * mode is meaningless there and would hang waiting for keystroke
 * events that never arrive.
 *
 * Handles common control chars: Ctrl+C aborts (exit 130), Ctrl+D
 * cancels (exit 1), Backspace edits the in-memory buffer. Multi-char
 * data chunks (paste) are processed char-by-char so a pasted password
 * containing a control char still triggers the right branch.
 */
async function readPasswordSilent(prompt: string): Promise<string> {
  process.stdout.write(prompt);
  const stdin = process.stdin;

  if (!stdin.isTTY) {
    const rl = createInterface({ input, output, terminal: false });
    const pw = await rl.question("");
    rl.close();
    return pw;
  }

  const wasRaw = stdin.isRaw;
  stdin.setRawMode(true);
  stdin.resume();
  stdin.setEncoding("utf8");

  return new Promise<string>((resolve) => {
    let buffer = "";
    const onData = (chunk: string) => {
      for (const c of chunk.toString()) {
        if (c === "\r" || c === "\n") {
          stdin.setRawMode(wasRaw);
          stdin.pause();
          stdin.removeListener("data", onData);
          process.stdout.write("\n");
          resolve(buffer);
          return;
        }
        if (c === "") {
          // Ctrl+C
          process.stdout.write("\n");
          process.exit(130);
        }
        if (c === "") {
          // Ctrl+D — treat as cancel
          process.stdout.write("\n");
          process.exit(1);
        }
        if (c === "" || c === "\b") {
          // DEL / Backspace
          buffer = buffer.slice(0, -1);
          continue;
        }
        buffer += c;
      }
    };
    stdin.on("data", onData);
  });
}

async function readPassword(): Promise<string> {
  const fromEnv = process.env.SYNTHESIS_DAEMON_KEYSTORE_PASSWORD;
  if (fromEnv && fromEnv.length >= 8) return fromEnv;
  return readPasswordSilent("Daemon keystore password: ");
}

function expandHome(path: string): string {
  if (path.startsWith("~/")) return `${homedir()}${path.slice(1)}`;
  return path;
}

async function main(): Promise<void> {
  const argv = process.argv.slice(2);
  const sepIdx = argv.indexOf("--");
  if (sepIdx === -1) {
    throw new Error(
      "expected `-- <command...>` separator. Example:\n" +
        "  pnpm tsx scripts/run-with-daemon-key.ts \\\n" +
        "    --keystore ~/.synthesis/daemon-trustrust-keystore.json \\\n" +
        "    -- ensemble agent register daemon.trustrust.eth --link true",
    );
  }
  const flags = argv.slice(0, sepIdx);
  const childArgv = argv.slice(sepIdx + 1);
  if (childArgv.length === 0) throw new Error("missing command after `--`");

  const ksFlag = flags.indexOf("--keystore");
  if (ksFlag === -1 || !flags[ksFlag + 1]) {
    throw new Error("--keystore <path> required");
  }
  const keystorePath = expandHome(flags[ksFlag + 1]);
  if (!existsSync(keystorePath)) {
    throw new Error(`keystore not found: ${keystorePath}`);
  }

  const password = await readPassword();
  const keystore = JSON.parse(readFileSync(keystorePath, "utf-8"));
  let privateKey: string | null = await decryptKeystore(keystore, password);

  const [cmd, ...cmdArgs] = childArgv;
  console.error(`(running with ENS_PRIVATE_KEY from ${keystorePath})`);
  const child = spawn(cmd, cmdArgs, {
    stdio: "inherit",
    env: { ...process.env, ENS_PRIVATE_KEY: privateKey },
  });
  // Zero out our reference once the child has it via env.
  privateKey = null;

  await new Promise<void>((resolve, reject) => {
    child.on("error", reject);
    child.on("exit", (code, signal) => {
      if (signal) {
        process.kill(process.pid, signal);
        return;
      }
      process.exit(code ?? 0);
      resolve();
    });
  });
}

main().catch((err) => {
  console.error(`\n[run-with-daemon-key] ${err instanceof Error ? err.message : err}`);
  process.exit(1);
});
